# -*- coding: utf-8 -*-
"""Stats-Sampling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhHsCh2iMaZgJgEva6xAXfySNMvepBVq
"""

!pip install -U imbalanced-learn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler, SMOTE
from sklearn.utils import resample

data = pd.read_csv("/content/Creditcard_data.csv")

print(data.head())
print(data['Class'].value_counts())

X = data.drop("Class", axis=1)
y = data["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rus = RandomUnderSampler(random_state=42)
X_rus, y_rus = rus.fit_resample(X_train, y_train)
print(y_rus.value_counts())

ros = RandomOverSampler(random_state=42)
X_ros, y_ros = ros.fit_resample(X_train, y_train)
print(y_rus.value_counts())

smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X_train, y_train)
print(y_rus.value_counts())

X_strat, y_strat = X_train, y_train
print(y_rus.value_counts())

X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=42
)
print(y_rus.value_counts())

models = {
    "M1_LogisticRegression": LogisticRegression(max_iter=1000),
    "M2_DecisionTree": DecisionTreeClassifier(),
    "M3_RandomForest": RandomForestClassifier(),
    "M4_KNN": KNeighborsClassifier(),
    "M5_NaiveBayes": GaussianNB()
}

samples = {
    "Sampling1_RUS": (X_rus, y_rus),
    "Sampling2_ROS": (X_ros, y_ros),
    "Sampling3_SMOTE": (X_smote, y_smote),
    "Sampling4_Stratified": (X_strat, y_strat),
    "Sampling5_Bootstrap": (X_boot, y_boot)
}

results = pd.DataFrame(index=models.keys(), columns=samples.keys())

for model_name, model in models.items():
    for sample_name, (Xs, ys) in samples.items():
        model.fit(Xs, ys)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        results.loc[model_name, sample_name] = round(acc * 100, 2)

print(results)

best_sampling = results.astype(float).idxmax(axis=1)
print("Best Sampling Technique per Model:\n")
print(best_sampling)

results.to_csv("sampling_results.csv")

print(results)

import matplotlib.pyplot as plt
import os

os.makedirs("graphs", exist_ok=True)

for model in results.index:
    plt.figure(figsize=(8,5))

    results.loc[model].astype(float).plot(kind="bar")

    plt.title(f"Accuracy Comparison for {model}")
    plt.xlabel("Sampling Techniques")
    plt.ylabel("Accuracy (%)")
    plt.xticks(rotation=45)
    plt.tight_layout()

    plt.savefig(f"graphs/{model}.png")

    plt.show()

    plt.close()

plt.figure(figsize=(8,5))

results.astype(float).mean().plot(kind="bar")

plt.title("Average Accuracy of Sampling Techniques")
plt.xlabel("Sampling Techniques")
plt.ylabel("Average Accuracy (%)")
plt.xticks(rotation=45)
plt.tight_layout()

plt.savefig("graphs/overall_sampling_performance.png")

plt.show()

plt.close()